### ISSUE TITLE
sorry, i can not find your paper?

### ISSUE THREAD

**Issue by daima2017** [JadeXIN/CycTEA#1]
sorry, i can not find your paper?

**Comment by JadeXIN** [comment]
Sorry for the late reply. Thank you for your interest in our work. Since the AAAI conference has not finished, I have not uploaded it to arxiv. Once I uploaded it, I will update the arxiv link in this repository.

**Comment by JadeXIN** [comment]
Hi, here is the arxiv link of our paper.
https://www.aaai.org/AAAI22Papers/AAAI-5065.XinK.pdf
Best Regards
